
SRC1 = $(wildcard guiao1/*.c)

OBJ1 = $(SRC1:.c=.o)

.PHONY: guiao1 all clean cout

all : mcat

mcat : $(OBJ1)
        gcc -o $@ $^

clean : 
        rm -f guiao1/*.o mcat

cout : 
        rm -f mcat
~                                                                                                                                     
~                           
